import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/period_cycle.dart';
import '../theme.dart';
import '../widgets/common.dart';

class HistoryScreen extends StatelessWidget {
 final List<PeriodCycle> cycles; final VoidCallback onLogPeriod; final ValueChanged<String> onDelete; final String? deletingId;
 const HistoryScreen({super.key,required this.cycles,required this.onLogPeriod,required this.onDelete,required this.deletingId});
 DateTime d(String s)=>DateTime.parse(s); int days(DateTime a,DateTime b)=>DateUtils.dateOnly(b).difference(DateUtils.dateOnly(a)).inDays;
 int get average{if(cycles.length<2)return 28;final v=<int>[];for(var i=0;i<cycles.length-1;i++){final n=days(d(cycles[i+1].periodStart),d(cycles[i].periodStart));if(n>0&&n<100)v.add(n);}return v.isEmpty?28:(v.reduce((a,b)=>a+b)/v.length).round();}
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.fromLTRB(20,28,20,50),children:[
  const Kicker('Your rhythm'),const SizedBox(height:10),const Text('Cycle history',style:TextStyle(fontSize:49,height:.98,fontWeight:FontWeight.w500,letterSpacing:-2.5)),const SizedBox(height:10),const Text('A quiet record of your cycle, month by month.',style:TextStyle(fontSize:11,color:AppColors.lightMuted)),const SizedBox(height:25),
  if(cycles.length>1)...[_chart(c),const SizedBox(height:28)],
  if(cycles.isEmpty) SoftCard(child:Column(children:[const Text('🌷',style:TextStyle(fontSize:42)),const SizedBox(height:9),const Text('Your story starts here.',style:TextStyle(fontSize:18,fontWeight:FontWeight.w600)),const SizedBox(height:7),const Text('Once you log a period, each month will appear here with its dates and cycle length.',style:TextStyle(fontSize:10,color:AppColors.lightMuted),textAlign:TextAlign.center),const SizedBox(height:15),PrimaryButton(label:'Log first period',icon:Icons.add,onPressed:onLogPeriod)]))
  else ...cycles.asMap().entries.map((e){final i=e.key,cy=e.value;final len=i+1<cycles.length?days(d(cycles[i+1].periodStart),d(cy.periodStart)):null;final dur=cy.periodEnd==null?null:days(d(cy.periodStart),d(cy.periodEnd!))+1;return Padding(padding:const EdgeInsets.only(bottom:12),child:Dismissible(key:ValueKey(cy.id),direction:DismissDirection.endToStart,background:Container(decoration:BoxDecoration(color:const Color(0xFFFFE4E6),borderRadius:BorderRadius.circular(20)),alignment:Alignment.centerRight,padding:const EdgeInsets.only(right:20),child:const Icon(Icons.delete_outline,color:AppColors.rose)),onDismissed:(_)=>onDelete(cy.id),child:SoftCard(padding:const EdgeInsets.symmetric(horizontal:18,vertical:15),child:Row(children:[Container(width:54,height:62,decoration:BoxDecoration(color:AppColors.roseSoft,borderRadius:BorderRadius.circular(15)),alignment:Alignment.center,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(DateFormat('MMM','en_IN').format(d(cy.periodStart)).toUpperCase(),style:const TextStyle(fontSize:8,color:AppColors.rose,fontWeight:FontWeight.w700)),Text('${d(cy.periodStart).day}',style:const TextStyle(fontSize:22,color:AppColors.rose,fontWeight:FontWeight.w500)),Text('${d(cy.periodStart).year}',style:const TextStyle(fontSize:8,color:AppColors.lightMuted))])),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${DateFormat('d MMM yyyy','en_IN').format(d(cy.periodStart))}${cy.periodStartTime==null?'':' · ${cy.periodStartTime}'}',style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(height:6),Text(cy.periodEnd==null?'End date not recorded':'Period ended ${DateFormat('d MMM yyyy','en_IN').format(d(cy.periodEnd!))}',style:const TextStyle(fontSize:9,color:AppColors.lightMuted))])),Column(crossAxisAlignment:CrossAxisAlignment.end,children:[if(len!=null)Text('$len days',style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:AppColors.rose)),if(dur!=null)Text('Period $dur d',style:const TextStyle(fontSize:9,color:AppColors.lightMuted))])]))));}),const SizedBox(height:16),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(border:Border(top:BorderSide(color:AppColors.lightMuted))),child:const Text('Cycle length is calculated from one period start to the next. Predictions are estimates and can naturally vary.',style:TextStyle(fontSize:9,color:AppColors.lightMuted,height:1.7)))
 ]);
 Widget _chart(BuildContext c){final v=cycles.take(9).toList().reversed.toList();final p=<int>[];for(var i=0;i<v.length-1;i++){p.add(days(d(v[i].periodStart),d(v[i+1].periodStart)));}if(p.isEmpty)return const SizedBox.shrink();final min=p.reduce((a,b)=>a<b?a:b)-4,max=p.reduce((a,b)=>a>b?a:b)+4;return SoftCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Kicker('Visual history'),const SizedBox(height:6),const Text('Your cycle, month by month · visual rhythm.',style:TextStyle(fontSize:18,fontWeight:FontWeight.w500)),const SizedBox(height:22),SizedBox(height:190,child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:List.generate(p.length,(i){final n=p[i];final h=((n-min)/(max-min)).clamp(.08,1.0);return Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text('$n',style:const TextStyle(fontSize:9,color:AppColors.lightMuted)),const SizedBox(height:4),Expanded(child:Align(alignment:Alignment.bottomCenter,child:FractionallySizedBox(heightFactor:h,child:Container(decoration:BoxDecoration(color:AppColors.rose.withOpacity(.75),borderRadius:BorderRadius.circular(10)))))),const SizedBox(height:7),Text(DateFormat('MMM','en_IN').format(d(v[i].periodStart)),style:const TextStyle(fontSize:8,color:AppColors.lightMuted))])));}))),const SizedBox(height:12),Text('Average · $average days',style:const TextStyle(fontSize:10,color:AppColors.lightMuted))]));}
}
