import 'package:flutter/material.dart';
import '../theme.dart';
import '../widgets/common.dart';

class UsScreen extends StatelessWidget {
 final int intimacyCount; final VoidCallback onAddMoment; final bool saving;
 const UsScreen({super.key,required this.intimacyCount,required this.onAddMoment,required this.saving});
 int get daysTogether=>DateUtils.dateOnly(DateTime.now()).difference(DateTime(2022,10,12)).inDays.clamp(0,99999);
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.fromLTRB(20,28,20,50),children:[
  const Kicker('A little more of us'),const SizedBox(height:12),const Text('Some dates are worth\nkeeping forever.',style:TextStyle(fontSize:49,height:.98,fontWeight:FontWeight.w500,letterSpacing:-2.5)),const SizedBox(height:16),const Text('Not everything beautiful needs a big explanation. Some things are simply worth remembering.',style:TextStyle(fontSize:11,color:AppColors.lightMuted,height:1.7)),const SizedBox(height:35),_together(c),const SizedBox(height:70),const Kicker('The dates that matter'),const SizedBox(height:8),const Text('A few days I’ll always remember.',style:TextStyle(fontSize:29,fontWeight:FontWeight.w500,letterSpacing:-1.1)),const SizedBox(height:20),_dates(c),const SizedBox(height:60),_memory(c,'A morning I’ll always remember','Our first selfie & first short outing.','1 January 2023 · Around 6:00 AM','Just a quiet walk around Spectrum School in the early morning — simple, peaceful, and special because it was one of our first little adventures together.'),const SizedBox(height:48),_memory(c,'A memory close to the heart','The day we became even closer.','3 March 2026','Some moments are not about the details. They are about trust, closeness, and the feeling of being completely present with each other.'),const SizedBox(height:55),_counter(c),const SizedBox(height:35),const Center(child:Text('♡  More memories waiting to be written.',style:TextStyle(fontSize:10,color:AppColors.rose,fontStyle:FontStyle.italic))) ]);
 Widget _together(BuildContext c)=>SoftCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Kicker('Since 12 October 2022'),const SizedBox(height:8),const Text('Still writing the story.',style:TextStyle(fontSize:28,fontWeight:FontWeight.w500,letterSpacing:-1)),const SizedBox(height:7),const Text('Every ordinary day becomes part of something that started on one very special day.',style:TextStyle(fontSize:10,color:AppColors.lightMuted,height:1.7)),const SizedBox(height:22),Text('$daysTogether',style:const TextStyle(fontSize:55,color:AppColors.rose,fontWeight:FontWeight.w500,letterSpacing:-3)),const Text('DAYS TOGETHER',style:const TextStyle(fontSize:8,color:AppColors.lightMuted,fontWeight:FontWeight.w700,letterSpacing:1.4))]));
 Widget _dates(BuildContext c){const list=[('12 Oct 2022','Our love anniversary','The day our story got its own date.'),('21 Oct 2004','Your birthday','The day the person behind all these memories arrived.'),('21 Feb 2005','My birthday','Another date that became part of our story.')];return LayoutBuilder(builder:(context,b)=>b.maxWidth>650?Row(children:list.map((x)=>Expanded(child:_dateCard(context,x.$1,x.$2,x.$3))).toList()):Column(children:list.map((x)=>_dateCard(context,x.$1,x.$2,x.$3)).toList()));}
 Widget _dateCard(BuildContext c,String dt,String title,String copy)=>Container(padding:const EdgeInsets.symmetric(horizontal:20,vertical:23),decoration:BoxDecoration(border:Border.all(color:Theme.of(c).dividerColor)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(dt.toUpperCase(),style:const TextStyle(fontSize:8,color:AppColors.rose,fontWeight:FontWeight.w700,letterSpacing:1.2)),const SizedBox(height:11),Text(title,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w600)),const SizedBox(height:7),Text(copy,style:const TextStyle(fontSize:9,color:AppColors.lightMuted,height:1.6))]));
 Widget _memory(BuildContext c,String k,String title,String dt,String copy)=>Container(padding:const EdgeInsets.fromLTRB(25,28,25,25),decoration:BoxDecoration(border:Border.all(color:const Color(0xFFEAD7DA)),borderRadius:BorderRadius.circular(22),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xFFFBEFF1),Color(0xFFFFFFFF)])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Kicker(k),const SizedBox(height:10),Text(title,style:const TextStyle(fontSize:29,fontWeight:FontWeight.w500,letterSpacing:-1.1)),const SizedBox(height:7),Text(dt,style:const TextStyle(fontSize:10,color:AppColors.lightMuted)),const SizedBox(height:20),Container(padding:const EdgeInsets.only(top:17),decoration:const BoxDecoration(border:Border(top:BorderSide(color:Color(0x29B95763)))),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('♡',style:TextStyle(fontSize:25,color:AppColors.rose)),const SizedBox(width:13),Expanded(child:Text(copy,style:const TextStyle(fontSize:10,color:Color(0xFF74696D),height:1.8,fontStyle:FontStyle.italic))) ]))]));
 Widget _counter(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(vertical:28),decoration:BoxDecoration(border:Border(top:BorderSide(color:AppColors.lightMuted),bottom:BorderSide(color:AppColors.lightMuted))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Kicker('Our little moments'),const SizedBox(height:8),const Text('A number only we need to understand.',style:TextStyle(fontSize:27,fontWeight:FontWeight.w500,letterSpacing:-1)),const SizedBox(height:6),const Text("For every moment we've shared that made us feel a little closer.",style:TextStyle(fontSize:10,color:AppColors.lightMuted,height:1.7)),const SizedBox(height:16),Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$intimacyCount',style:const TextStyle(fontSize:47,color:AppColors.rose,fontWeight:FontWeight.w500,letterSpacing:-2)),const Text('LITTLE MOMENTS',style:const TextStyle(fontSize:8,color:AppColors.lightMuted,fontWeight:FontWeight.w700,letterSpacing:1.3))])),PrimaryButton(label:'Add one',icon:Icons.favorite,onPressed:saving?null:onAddMoment,loading:saving)])]));
}
